import jdk.jfr.Percentage;

import java. security.SecureRandom;
import java.util.Scanner;
import java.lang.Double;


public class Smith_P1 {
    public static double generateQuest( double diffi_num1, double diffi_num2) {
        double num1, num2;
        double ans;
        int Opp1;
        num1 = 0;
        num2 = 0;

        // Generate random number
        SecureRandom rand = new SecureRandom();

        //sets the values of num 1 and num 2 equal to the numbers generated by the dfficulty method
        num1=diffi_num1;
        num2=diffi_num2;

        //makes a random opperation and then prints out the problem while also generating the answer
        Opp1 = rand.nextInt(4);

        if (Opp1 == 0) {
            ans = num1 + num2;
            System.out.println("What does " + num1 + " + " + num2 + " = ");
        } else if (Opp1 == 1) {
            ans = num1 - num2;
            System.out.println("What does " + num1 + " - " + num2 + " = ");
        } else if (Opp1 == 2) {
            ans = num1 * num2;
            System.out.println("What does " + num1 + " * " + num2 + " = ");
        } else {
            if (num2==0)
                ans=0;
            else {
                ans = num1 / num2;

            }
            System.out.println("What does " + num1 + " / " + num2 + " = ");
        }


        return ans;
    }

    public static int responses(int ans) {
        int resp;

        SecureRandom rand = new SecureRandom();


        //Generates a random number between 0 to 3 and the number corresponds to a response
        //this is for both correct and incorrect
        resp = rand.nextInt(4);

        if (ans == 0) {

            switch (resp) {
                case 0:
                    System.out.println("Es muy Caliente!!!!!!");
                    break;
                case 1:
                    System.out.println("Very Good!");
                    break;
                case 2:
                    System.out.println("Excellent!");
                    break;
                case 3:
                    System.out.println("Keep up the good work!");
                    break;
            }

        } else {
            switch (resp) {
                case 0:
                    System.out.println("No. Please try again");
                    break;
                case 1:
                    System.out.println("Wrong. Try once more.");
                    break;
                case 2:
                    System.out.println("Don't give up!");
                    break;
                case 3:
                    System.out.println("No. Keep trying!");
                    break;
            }


        }

        return 0;
    }

    public static double difficulty(int difficulty_Level){
        double ran_num;
        //initialize values to reset to zero everytime the function is called
        ran_num=0;

        // Generate random number
        SecureRandom rand = new SecureRandom();

        //Assign the two numbers to a random variable
        if (difficulty_Level == 1) {
            ran_num = rand.nextInt(10);

        } else if (difficulty_Level == 2) {
            ran_num= rand.nextInt(100);

        } else if (difficulty_Level == 3) {
            ran_num= rand.nextInt(1000);
        } else if (difficulty_Level == 4) {
            ran_num = rand.nextInt(10000);

        }

        return ran_num;
    }

    public static double study(int choice, double diffi_num1, double diffi_num2) {
        double num1, num2, ans;
        int Opp1;
        num1 = 0;
        num2 = 0;
        Opp1 = 0;
        ans = 0;

        // Generate random number
        SecureRandom rand = new SecureRandom();

        //Assign the two numbers to a random variable from difficulty
        num1=diffi_num1;
        num2=diffi_num2;

        //makes a random opperation and then prints out the problem while also generating the answer
        if (choice == 1) {
            Opp1 = 0;
        } else if (choice == 2) {
            Opp1 = 1;
        } else if (choice == 3) {
            Opp1 = 2;
        } else if (choice == 4) {
            Opp1 = 3;
        } else if (choice == 5) {
            Opp1 = rand.nextInt(4);
        }

        if (Opp1 == 0) {
            ans = num1 + num2;
            System.out.println("What does " + num1 + " + " + num2 + " = ");
        } else if (Opp1 == 1) {
            ans = num1 - num2;
            System.out.println("What does " + num1 + " - " + num2 + " = ");
        } else if (Opp1 == 2) {
            ans = num1 * num2;
            System.out.println("What does " + num1 + " * " + num2 + " = ");
        } else if (Opp1 == 3) {
            ans = num1 / num2;
            System.out.println("What does " + num1 + " / " + num2 + " = ");
        }


        return ans;
    }


    public static void main(String[] args) {
        double corrAns, userAns,numA,numB;
        int ansresp, getResp, percentageRight, difficulty, input, difficulty2, input2, input3, input4,choicecont;



        Scanner scnr = new Scanner(System.in);
        do {
            percentageRight = 0;
            input = 0;
            difficulty = 1;
            input4 = 0;
            choicecont=0;
            while (input != 1) {
                System.out.println("Please enter a difficulty level: ");
                System.out.println("1- Single digit number (0-9)");
                System.out.println("2- Double digit numbers (0-99)");
                System.out.println("3- Triple digit numbers (0-999)");
                System.out.println("4- Quadruple Digit numbers (0-9999)");

                difficulty = scnr.nextInt();
                if (difficulty > 4 || difficulty < 1) {
                    System.out.println("I'm sorry but you can only pick between 1 and 4");
                    input = 0;

                } else
                    input = 1;
            }


            //repeat the questions 10 times over with each time being a different question
            for (int i = 0; i < 10; i++) {
                //Gets the correct question while making the question too
                numA=difficulty(difficulty);
                numB=difficulty(difficulty);
                corrAns = generateQuest(numA,numB);

                //Gets the input of the user's answer
                userAns = scnr.nextDouble();


                //If else statement to print out correct or incorrect
                if (Double.compare(userAns,corrAns)==0) {
                    ansresp = 0;
                    percentageRight = percentageRight + 1;
                    getResp = responses(ansresp);
                } else {
                    ansresp = 1;
                    getResp = responses(ansresp);
                    System.out.println("The correct answer is: " + corrAns);
                    System.out.println("Your answer: " + userAns);
                }
            }

            System.out.println("Number of answers correct:" + percentageRight);
            System.out.println("Number of incorrect answers: " + (10 - percentageRight));

            if (percentageRight >= 8) {
                System.out.println("Congratulations, you are ready to go to the next level!");
            } else
                System.out.println("Please ask your teacher for extra help.");

            input2 = 0;
            difficulty2 = 0;
            System.out.println("Would you like to study a few problems?");
            System.out.println("0- No");
            System.out.println("1- Yes");
            input2 = scnr.nextInt();
            if (input2 == 0) {

            } else if (input2 == 1) {
                System.out.println("1- Addition problems only");
                System.out.println("2- Multiplication problems only");
                System.out.println("3- Subtraction Problems only");
                System.out.println("4- Division problems only");
                System.out.println("5- Mixture of different problems");
                input3 = scnr.nextInt();

                while (input4 != 1) {
                    System.out.println("Please enter a difficulty level: ");
                    System.out.println("1- Single digit number (0-9)");
                    System.out.println("2- Double digit numbers (0-99)");
                    System.out.println("3- Triple digit numbers (0-999)");
                    System.out.println("4- Quadruple Digit numbers (0-9999)");

                    difficulty2 = scnr.nextInt();
                    if (difficulty2 > 4 || difficulty2 < 1) {
                        System.out.println("I'm sorry but you can only pick between 1 and 4");
                        input4 = 0;

                    } else
                        input4 = 1;
                }


                //repeat the questions 10 times over with each time being a different question
                for (int i = 0; i < 10; i++) {
                    numA=0;
                    numB=0;
                    numA=difficulty(difficulty2);
                    numB=difficulty(difficulty2);
                    //Gets the correct question while making the question too
                    corrAns = study(input3,numA,numB);

                    //Gets the input of the user's answer
                    userAns = scnr.nextInt();

                    //If else statement to print out correct or incorrect
                    if (userAns == corrAns) {
                        ansresp = 0;
                        percentageRight = percentageRight + 1;
                        getResp = responses(ansresp);
                    } else {
                        ansresp = 1;
                        getResp = responses(ansresp);
                    }
                }


            }
            System.out.print("Would you like to start a new session? 0=Yes, 1=No");
            choicecont=scnr.nextInt();




        }while(choicecont !=1);
        System.out.println("Thank you and goodbye!");
        scnr.close();
    }


}

